apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bigtwine
  region: eu-central-1
  version: "1.14"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: jobsupervisor
      namespace: bigtwine
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"

nodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    desiredCapacity: 5
    minSize: 1
    maxSize: 5
    kubeletExtraConfig:
      kubeReserved:
        cpu: "200m"
        memory: "200Mi"
        ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
        cpu: "200m"
        memory: "200Mi"
        ephemeral-storage: "1Gi"
      evictionHard:
        memory.available:  "200Mi"
        nodefs.available: "10%"
      featureGates:
        DynamicKubeletConfig: true
        RotateKubeletServerCertificate: true
