apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: bigtwine
  labels:
    app: apigateway
spec:
  selector:
    app: apigateway
  type: NodePort
  ports:
  - name: http
    port: 9000
