apiVersion: v1
kind: Secret
metadata:
  name: app-encryptors-secret
  namespace: bigtwine
type: Opaque
data:
  secret: '{{APP_ENCRYPTORS_SECRET_SECRET}}' # base64 encoded secret to use with spring encryptors
  salt: '{{APP_ENCRYPTORS_SECRET_SALT}}' # base64 encoded salt to use with spring encryptors
---
apiVersion: v1
kind: Secret
metadata:
  name: twitter-api-secret
  namespace: bigtwine
type: Opaque
data:
  consumer-key: '{{TWITTER_API_SECRET_CONSUMER_KEY}}' # base64 encoded twitter app consumer key
  consumer-secret: '{{TWITTER_API_SECRET_CONSUMER_SECRET}}' # base64 encoded twitter app consumer secret
  access-token: '{{TWITTER_API_SECRET_ACCESS_TOKEN}}' # base64 encoded twitter demo user access token
  access-secret: '{{TWITTER_API_SECRET_ACCESS_SECRET}}' # base64 encoded twitter demo user access secret
