apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bigtwine
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
