apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bigtwine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: "v1"
  template:
    metadata:
      labels:
        app: frontend
        version: "v1"
    spec:
      nodeSelector:
        role: primary
      containers:
      - name: frontend-app
        image: 535233662260.dkr.ecr.eu-central-1.amazonaws.com/bigtwine/frontend:0.9.2
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - name: http
          containerPort: 80
