apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bigtwine
  region: eu-central-1
  version: "1.14"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: jobsupervisor
      namespace: bigtwine
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"

managedNodeGroups:
  - name: ng-primary
    # desiredCapacity: 3
    # instanceType: c5.xlarge
    desiredCapacity: 4
    instanceType: t3a.medium
    labels: { role: primary }
    availabilityZones:
      - eu-central-1a
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        albIngress: true
  - name: ng-secondary
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    instanceType: t3a.medium
    labels: { role: secondary }
    availabilityZones:
      - eu-central-1a
    iam:
      withAddonPolicies:
        autoScaler: true
