apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bigtwine
  region: eu-central-1
  version: "1.14"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: jobsupervisor
      namespace: bigtwine
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"

nodeGroups:
  - name: ng-1
    minSize: 1
    maxSize: 3
    availabilityZones: ["eu-central-1a"]
    instancesDistribution:
      maxPrice: 0.008
      instanceTypes: ["t3.medium", "t3.large", "c5.xlarge"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 33
      spotInstancePools: 2
    kubeletExtraConfig:
      kubeReserved:
        cpu: "50m"
        memory: "100Mi"
        ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
        cpu: "50m"
        memory: "100Mi"
        ephemeral-storage: "1Gi"
      evictionHard:
        memory.available:  "200Mi"
        nodefs.available: "10%"
      featureGates:
        DynamicKubeletConfig: true
        RotateKubeletServerCertificate: true
  - name: ng-2
    minSize: 1
    maxSize: 3
    availabilityZones: ["eu-central-1b"]
    instancesDistribution:
      maxPrice: 0.008
      instanceTypes: ["t3.medium", "t3.large", "c5.xlarge"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 33
      spotInstancePools: 2
    kubeletExtraConfig:
      kubeReserved:
        cpu: "50m"
        memory: "100Mi"
        ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
        cpu: "50m"
        memory: "100Mi"
        ephemeral-storage: "1Gi"
      evictionHard:
        memory.available:  "200Mi"
        nodefs.available: "10%"
      featureGates:
        DynamicKubeletConfig: true
        RotateKubeletServerCertificate: true
  - name: ng-3
    minSize: 1
    maxSize: 3
    availabilityZones: ["eu-central-1c"]
    instancesDistribution:
      maxPrice: 0.008
      instanceTypes: ["t3.medium", "t3.large", "c5.xlarge"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 33
      spotInstancePools: 2
    kubeletExtraConfig:
      kubeReserved:
        cpu: "50m"
        memory: "100Mi"
        ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
        cpu: "50m"
        memory: "100Mi"
        ephemeral-storage: "1Gi"
      evictionHard:
        memory.available:  "200Mi"
        nodefs.available: "10%"
      featureGates:
        DynamicKubeletConfig: true
        RotateKubeletServerCertificate: true
