apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: analysisautoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analysis
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75