apiVersion: apps/v1
kind: Deployment
metadata:
  name: ner
  namespace: bigtwine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ner
      version: "v1"
  template:
    metadata:
      labels:
        app: ner
        version: "v1"
    spec:
      initContainers:
        - name: init-ds
          image: busybox
          command:
            - '/bin/sh'
            - '-c'
            - |
                while true
                do
                  if [ $? -eq 0 ]; then
                    echo "DB is UP"
                    break
                  fi
                  echo "DB is not yet reachable;sleep for 10s before retry"
                  sleep 10
                done
      containers:
      - name: ner-app
        image: bigtwine/ner:1.0.0
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:${jhipster.registry.password}@jhipster-registry.bigtwine.svc.cluster.local:8761/config
        - name: JHIPSTER_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: registry-admin-password
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:${jhipster.registry.password}@jhipster-registry.bigtwine.svc.cluster.local:8761/eureka/
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: jhipster-kafka.bigtwine.svc.cluster.local
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
          value: jhipster-zookeeper.bigtwine.svc.cluster.local
        - name: JHIPSTER_METRICS_LOGS_ENABLED
          value: 'true'
        - name: JHIPSTER_LOGGING_LOGSTASH_ENABLED
          value: 'true'
        - name: JHIPSTER_LOGGING_LOGSTASH_HOST
          value: jhipster-logstash
        - name: SPRING_ZIPKIN_ENABLED
          value: "true"
        - name: SPRING_ZIPKIN_BASE_URL
          value: http://jhipster-zipkin
        - name: SPRING_SLEUTH_PROPAGATION_KEYS
          value: "x-request-id,x-ot-span-context"
        - name: JAVA_OPTS
          value: " -Xmx256m -Xms256m"
        - name: APPLICATION_PROCESSORS_RITTER_WORKINGDIRECTORY
          value: "/data"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - name: http
          containerPort: 9002
        readinessProbe:
          httpGet:
            path: /management/health
            port: http
          initialDelaySeconds: 20
          periodSeconds: 15
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /management/health
            port: http
          initialDelaySeconds: 120
        volumeMounts:
          - mountPath: /data
            name: ner-share
      - name: ner-tool
        image: bigtwine/ner-tool
        volumeMounts:
          - mountPath: /data
            name: ner-share
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1"
        env:
        - name: JVM_OPTS
          value: "-Xms64M -Xmx1536M"
      volumes:
        - name: ner-share
          emptyDir: {}
